---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-local-0
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi

  accessModes:
    - ReadWriteOnce

  volumeMode: Filesystem

  persistentVolumeReclaimPolicy: Retain

  storageClassName: local-storage

  hostPath:
    path: /tmp
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-local-1
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi

  accessModes:
    - ReadWriteOnce

  volumeMode: Filesystem

  persistentVolumeReclaimPolicy: Retain

  storageClassName: local-storage

  hostPath:
    path: /tmp
