---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: tcp

      - containerPort: 443
        hostPort: 443
        protocol: tcp

      - containerPort: 32080
        hostPort: 32080
        protocol: tcp

      - containerPort: 32081
        hostPort: 32081
        protocol: tcp

      - containerPort: 32082
        hostPort: 32082
        protocol: tcp

      - containerPort: 32443
        hostPort: 32443
        protocol: tcp

  - role: worker
  - role: worker
  - role: worker
