#!/bin/bash

# export AWS_ACCESS_KEY=""
# export AWS_SECRET_KEY=""

AWS_CREDENTIALS_FILE_BASE64_ENCODED=$(
  cat <<EOF | base64 -w 0
[default]
aws_access_key_id = ${AWS_ACCESS_KEY?}
aws_secret_access_key = ${AWS_SECRET_KEY?}
EOF
)

kubectl apply -f - <<EOF
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: crossplane-system
type: Opaque
data:
  creds: ${AWS_CREDENTIALS_FILE_BASE64_ENCODED?}
EOF

cat <<EOF | kubectl apply -f -
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-contrib-provider-aws-s3
spec:
  package: xpkg.crossplane.io/crossplane-contrib/provider-aws-s3:v2.0.0
EOF

kubectl get providers

cat <<EOF | kubectl apply -f -
apiVersion: aws.m.upbound.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-secret
      key: creds
EOF

cat <<EOF | kubectl create -f -
apiVersion: s3.aws.m.upbound.io/v1beta1
kind: Bucket
metadata:
  namespace: default
  generateName: crossplane-bucket-
spec:
  forProvider:
    region: us-east-2
EOF

kubectl get buckets
