---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-example-com-self-signed
spec:
  issuerRef:
    kind: ClusterIssuer
    name: self-signed

  commonName: app.example.com
  
  dnsNames:
    - app.example.com

  secretName: app-example-com-self-signed
