---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-nginx
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory

    email: alerts@silvios.me

    privateKeySecretRef:
      name: letsencrypt-production-nginx-issuer-account-key

    solvers:
      - http01:
          ingress:
            class: nginx

            ingressTemplate:
              metadata:
                labels:
                  type: "challenge"
