global:
  cluster: "k3d-001"
  customSecretName: "nri-bundle"
  customSecretLicenseKey: "license"

newrelic-infrastructure:
  enabled: true
  privileged: true
  ksm:
    resources:
      limits:
        memory: 2G

nri-prometheus:
  enabled: false

nri-metadata-injection:
  enabled: false

kube-state-metrics:
  enabled: false
  image:
    tag: v2.7.0

nri-kube-events:
  enabled: false

newrelic-logging:
  enabled: false
  fluentBit:
    criEnabled: true

newrelic-pixie:
  enabled: false

pixie-chart:
  enabled: false

newrelic-infra-operator:
  enabled: false

newrelic-prometheus-agent:
  enabled: false
  lowDataMode: true
  config:
    kubernetes:
      integrations_filter:
        enabled: false
    extra_scrape_configs:
      - job_name: 'kubernetes-apiservers'
        
        kubernetes_sd_configs:
          - role: endpoints
        
        scheme: https
        
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep 
            regex: default;kubernetes;https

        metric_relabel_configs:
          - source_labels: [__name__]
            regex: "\
              apiserver_flowcontrol_current_inqueue_requests|\
              etcd_db_total_size_in_bytes|\
              process_resident_memory_bytes"
            action: keep

newrelic-k8s-metrics-adapter:
  enabled: false
