#!/bin/bash

if [[ -z "${AWS_ACCESS_KEY?}" ]]; then
  echo "AWS_ACCESS_KEY environment variable is not set"
  exit 1
fi

if [[ -z "${AWS_SECRET_KEY?}" ]]; then
  echo "AWS_SECRET_KEY environment variable is not set"
  exit 1
fi

aws_credentials_file_base64_encoded=$(
  cat <<EOF | base64 -w 0
[default]
aws_access_key_id = ${AWS_ACCESS_KEY?}
aws_secret_access_key = ${AWS_SECRET_KEY?}
EOF
)

kubectl apply -f - <<EOF
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: crossplane-system
type: Opaque
data:
  credentials: ${aws_credentials_file_base64_encoded?}
EOF
