---
- hosts: nodes
  name: Configure Node
 
  vars_files:
    - openstack/vars/openstack.yml
 
  tasks:
  
  - name: system update
    yum:
      name: "*"
      state: latest

  - name: add docker-ce repo
    yum_repository:
      name: "Docker-CE-Stable"
      description: "Docker CE Stable Yum Repo"
      baseurl: "https://download.docker.com/linux/centos/7/$basearch/stable"
      enabled: yes
      gpgcheck: yes
      gpgkey: "https://download.docker.com/linux/centos/gpg"

  - name: install docker-ce
    yum:
      name: "docker-ce"
      state: latest

  - name: configure docker service
    systemd:
      name: docker
      state: started
      enabled: yes

  - name: config user 'centos' appending the group 'docker'
    user:
      name: centos
      groups: docker
      append: yes

