server:
  service:
    type: LoadBalancer
    nodePortHttp: 32080
    nodePortHttps: 32444
    servicePortHttp: 80
    servicePortHttps: 443
    servicePortHttpName: http
    servicePortHttpsName: https
    namedTargetPort: true
