#!/bin/bash
kubectl config set-context minikube --namespace dev

kubectl delete -f . &> /dev/null

eval $(minikube docker-env)

docker rmi -f $(docker images | grep -E "^nginx" | awk '{ print $3 }') > /dev/null

watch -n 3 kubectl -n dev get deploy,rs,pods,svc
