---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 32080
        hostPort: 32080
        protocol: tcp

  - role: worker
  - role: worker
  - role: worker
