#!/usr/bin/env bash

AMQP_CONNECTION_URL="amqp://${RABBITMQ_USERNAME?}:${RABBITMQ_PASSWORD?}@${RABBITMQ_HOST?}:${RABBITMQ_PORT?}/${RABBITMQ_VIRTUAL_HOST?}"

kubectl \
  --namespace wasp \
  apply -f - <<EOF
---
apiVersion: v1
kind: Secret
metadata:
   name: keda-rabbitmq-secret
stringData:
  host: "${AMQP_CONNECTION_URL}"
EOF
