#!/usr/bin/env bash
export THIS_SCRIPT_DIRECTORY=$(dirname $0)
export PATH=${PATH}:${THIS_SCRIPT_DIRECTORY}

AMQP_CONNECTION_URL="amqp://${RABBITMQ_USERNAME?}:${RABBITMQ_PASSWORD?}@${RABBITMQ_HOST?}:${RABBITMQ_PORT?}/${RABBITMQ_VIRTUAL_HOST?}"

BASE64ENCODED_AMQP_CONNECTION_URL=$(echo -n "${AMQP_CONNECTION_URL?}" | base64 | tr -d "\n")

kubectl \
  --namespace wasp \
  apply -f - <<EOF
---
apiVersion: v1
kind: Secret
metadata:
   name: keda-rabbitmq-secret
data:
  host: ${BASE64ENCODED_AMQP_CONNECTION_URL}
EOF
