apiVersion: v1
kind: Pod
metadata:
  name: pod-3
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]

      envFrom:
        - configMapRef:
            name: my-config
