apiVersion: v1
kind: Pod
metadata:
  name: pod-2
spec:
  volumes:
    - name: configuration
      configMap:
        name: my-config

  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      
      volumeMounts:
        - name: configuration
          mountPath: "/etc/config"
          readOnly: true
