---
apiVersion: v1
kind: Pod
metadata:
  name: mongoshell
spec:
  restartPolicy: Never
 
  containers:
    - name: mongoshell
      image: silviosilva/mongoshell:2.0.2
      imagePullPolicy: Never      

      envFrom:
        - secretRef:
            name: mongoshell

      command:
        - sleep
        - infinity
