#!/bin/bash
echo "AZ_USER_ID.................: ${AZ_USER_ID}"
echo "AZ_USER_EMAIL..............: ${AZ_USER_EMAIL}"
echo "AZ_AKS_REGION..............: ${AZ_AKS_REGION}"
echo "AZ_AKS_RESOURCE_GROUP_NAME.: ${AZ_AKS_RESOURCE_GROUP_NAME}"
echo "AZ_AKS_CLUSTER_NAME........: ${AZ_AKS_CLUSTER_NAME}"
echo "AZ_AKS_CLUSTER_VERSION.....: ${AZ_AKS_CLUSTER_VERSION}"
echo "AZ_AKS_ADMIN_GROUP_ID......: ${AZ_AKS_ADMIN_GROUP_ID}"
echo "AZ_AKS_ADMIN_GROUP_NAME....: ${AZ_AKS_ADMIN_GROUP_NAME}"
