# Um tenant não estará necessariamente nas mesmas regiões que a plataforma
# Ele pode estar em um subconjunto ou até mesmo em regiões diferentes.
# Ao se comunicar com os serviços compartilhados, o Global Accelerator vai direcionar o tráfego para a região mais próxima do tenant.
# Um Tenant pode ter uma ou mais regiões, dependendo de onde estão seus clientes e de suas necessidades de latência e disponibilidade.
# As regiões inicialmente estarão configuradas como hot/warm.
# Ao ser redirecionado para um tenant como wayland.wasp.silvios.me, o Global Accelerator vai direcionar o tráfego para a região mais próxima do cliente,
# que pode ser ap-northeast-1 ou ap-southeast-1, dependendo da localização do cliente e de quais regiões estão ativas para esse tenant.
---
kind: tenant
name: wayland
spec:
  platform: wasp # domain: wayland.wasp.silvios.me

  regions:
    - name: ap-northeast-1
      endpoint: tenant-wasp-wayland-58015491.elb.ap-northeast-1.amazonaws.com

    - name: ap-southeast-1
      endpoint: tenant-wasp-wayland-26934e62.elb.ap-southeast-1.amazonaws.com
---
kind: tenant
name: sales
spec:
  platform: wasp # domain: sales.wasp.silvios.me

  regions:
    - name: us-east-1
      endpoint: tenant-wasp-sales-0aaecca4.elb.us-east-1.amazonaws.com
---
kind: tenant
name: demo
spec:
  platform: wasp

  regions:
    - name: us-east-1
      endpoint: tenant-wasp-demo-0aaecca4.elb.us-east-1.amazonaws.com
