#!/bin/bash
kubectl -n wasp apply -f - <<EOF
---
apiVersion: v1
kind: Secret
metadata:
  name: mongoshell
type: Opaque
stringData:
  MONGODB_HOST:          ${MONGODB_HOST}
  MONGODB_DATABASE_NAME: ${MONGODB_DATABASE_NAME}
  MONGODB_USERNAME:      ${MONGODB_USERNAME}
  MONGODB_PASSWORD:      ${MONGODB_PASSWORD}
EOF

kubectl -n wasp apply -f pod.yaml
kubectl -n wasp apply -f serviceentry.yaml
