#!/bin/bash
BASE64ENCODED_MONGODB_HOST=$(          echo -n "${MONGODB_HOST?}"          | base64 | tr -d "\n") && \
BASE64ENCODED_MONGODB_DATABASE_NAME=$( echo -n "${MONGODB_DATABASE_NAME?}" | base64 | tr -d "\n") && \
BASE64ENCODED_MONGODB_USERNAME=$(      echo -n "${MONGODB_USERNAME?}"      | base64 | tr -d "\n") && \
BASE64ENCODED_MONGODB_PASSWORD=$(      echo -n "${MONGODB_PASSWORD?}"      | base64 | tr -d "\n") && \
kubectl apply -f - <<EOF
---
apiVersion: v1
kind: Secret
metadata:
  name: mongoshell
type: Opaque
data:
  MONGODB_HOST:          ${BASE64ENCODED_MONGODB_HOST}
  MONGODB_DATABASE_NAME: ${BASE64ENCODED_MONGODB_DATABASE_NAME}
  MONGODB_USERNAME:      ${BASE64ENCODED_MONGODB_USERNAME}
  MONGODB_PASSWORD:      ${BASE64ENCODED_MONGODB_PASSWORD}
EOF
