#!/bin/bash

mongosh "mongodb+srv://${MONGODB_HOST?}/${MONGODB_DATABASE_NAME?}" \
  --username ${MONGODB_USERNAME?} \
  --password ${MONGODB_PASSWORD?} \
  --eval 'show collections'

mongosh "mongodb+srv://${MONGODB_HOST?}/${MONGODB_DATABASE_NAME?}" \
  --username ${MONGODB_USERNAME?} \
  --password ${MONGODB_PASSWORD?} \
  --eval 'printjson(db.version())' \
  --eval 'show collections'

mongosh "mongodb+srv://${MONGODB_HOST?}/${MONGODB_DATABASE_NAME?}" \
  --username ${MONGODB_USERNAME?} \
  --password ${MONGODB_PASSWORD?} \
  --file listPosts.js


# Upload file
az storage file upload \
  --account-name "${ARM_STORAGE_ACCOUNT_NAME}" \
  --account-key "${ARM_ACCESS_KEY}" \
  --share-name "troubleshooting" \
  --path capture.cap \
  --source capture.cap

az storage blob upload \
  --account-name "${ARM_STORAGE_ACCOUNT_NAME}" \
  --account-key "${ARM_ACCESS_KEY}" \
  --container-name "troubleshooting" \
  --file "capture.cap" \
  --overwrite
