#!/bin/bash
kubectl \
  --namespace example \
  get pods,service,endpoints,secrets,ingress \
  --output wide

echo ""

kubectl \
  --namespace ingress-nginx \
  logs \
  --selector app.kubernetes.io/component=controller \
  --tail 5
