#!/bin/bash
kubectl \
  --namespace httpbin \
  get pods,service,endpoints,ingress \
  --output wide

echo ""

kubectl \
  --namespace ingress-nginx \
  logs \
  --selector app.kubernetes.io/component=controller \
  --tail 10
