#!/bin/bash
kubectl create namespace httpbin

kubectl apply \
  --namespace httpbin \
  --filename httpbin/deployment.yaml

kubectl apply \
  --namespace httpbin \
  --filename httpbin/service.yaml

kubectl \
  --namespace httpbin \
  wait deploy httpbin \
  --for=condition=Available \
  --timeout=360s

nginx/run

kubectl apply \
  --namespace httpbin \
  --filename httpbin/ingress.yaml

BASE_DOMAIN="sandbox.wasp.silvios.me"

if ! grep --quiet httpbin.${BASE_DOMAIN?} /etc/hosts; then
  echo "127.0.0.1 httpbin.${BASE_DOMAIN?}" \
  | sudo tee -a /etc/hosts
fi

curl \
  --include \
  --header "host: httpbin.${BASE_DOMAIN?}" \
  127.0.0.1/get

exit 0

CERTIFICATE_DIRECTORY="${HOME}/certificates/${BASE_DOMAIN?}/production"

kubectl \
  --namespace httpbin \
  create secret tls \
  tls-${BASE_DOMAIN//./-} \
  --key "${CERTIFICATE_DIRECTORY}/certificate.key.pem" \
  --cert "${CERTIFICATE_DIRECTORY}/certificate.pem"
