---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-connection
spec:
  restartPolicy: Never

  initContainers:
    - name: sleep
      image: busybox
      command:
        - sh
        - -c
        - sleep 3

  containers:
    - name: psql
      image: postgres:12
      command: ['psql']
      args: ['-c', 'SELECT current_database();']

      envFrom:
        - secretRef:
            name: postgres
