apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test
  labels:
    app: app-test
spec:
  replicas: 1

  selector:
    matchLabels:
      app: app-test

  template:
    metadata:
      labels:
        app: app-test

      annotations:
        telemetry.silvios.me/agent-name: "app-agent-test"
        telemetry.silvios.me/agent-id: "12"

    spec:
      containers:
        - name: utils
          image: silviosilva/utils
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo $(date) && sleep 5; done"]
