---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tls-echo
spec:
  gatewayClassName: nginx

  listeners:
  - name: http 
    protocol: HTTP
    port: 80

  - name: https
    protocol: HTTPS
    port: 443
    hostname: "*.wasp.silvios.me"
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        group: ""
        name: tls-wasp-silvios-me
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo-route
spec:
  parentRefs:
  - name: tls-echo

  hostnames:
  - "*.wasp.silvios.me"

  rules:
  - backendRefs:
    - name: httpbin
      port: 80
