apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myserver
  name: myserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myserver
  template:
    metadata:
      labels:
        app: myserver
    spec:
      containers:
      - image: datawire/telepresence-k8s:0.105
        name: telepresence-k8s
        ports:
        - protocol: TCP
          containerPort: 8080
