---
apiVersion: v1
kind: Service
metadata:
  name: host-hello
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Endpoints
metadata:
  name: host-hello
subsets:
  - addresses:
      - ip: 172.17.0.1
    ports:
      - port: 8000
