apiVersion: v1
kind: Service
metadata:
  labels:
    app: myserver
  name: myserver
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: myserver
  type: LoadBalancer
