---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-actuator-demo
  name: spring-actuator-demo
spec:
  replicas: 1

  selector:
    matchLabels:
      app: spring-actuator-demo

  template:
    metadata:
      labels:
        app: spring-actuator-demo

      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      volumes:
        - name: logs
          emptyDir: {}

      containers:
        - name: spring-actuator-demo
          image: spring-actuator-demo:latest # docker.io/silviosilva/spring-actuator-demo:latest
          imagePullPolicy: Never # [Always, Never, IfNotPresent]

          ports:
            - containerPort: 8080
              name: http
          
            - containerPort: 9091
              name: management
          
          envFrom:
            - configMapRef:
                name: spring-actuator-demo

          volumeMounts:
            - name: logs
              mountPath: /var/log/
              readOnly: false
