---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-atlas
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: azure

  target:
    name: mongodb-atlas
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: secret/mongodb-atlas-user

    - secretKey: password
      remoteRef:
        key: secret/mongodb-atlas-password
