---
apiVersion: v1
kind: Service
metadata:
  name: hpa-example-canary
  labels:
    app: hpa-example
spec:
  ports:
    - port: 80

  selector:
    app: hpa-example
    type: canary
---
apiVersion: v1
kind: Service
metadata:
  name: hpa-example-release
  labels:
    app: hpa-example
spec:
  ports:
    - port: 80

  selector:
    app: hpa-example
    type: release
