#!/bin/bash
kubectl get Gateway -A

echo ""

kubectl -n istio-ingress get svc

echo ""

kubectl \
  get secret tls-wildcard-full-chain \
  --namespace istio-ingress 2> /dev/null || echo "istio-ingress/tls-wildcard-full-chain not found"

echo ""

kubectl -n example get VirtualService

echo ""

kubectl get pods -A -o wide | egrep "^NAMESPACE|^default|^example|^istio-ingress.*ingress"

echo ""

kubectl -n example get svc -o wide
