#!/bin/bash
export THIS_SCRIPT_DIRECTORY=$(dirname $0)
export PATH=${PATH}:${THIS_SCRIPT_DIRECTORY}

# Create Kind Cluser
echo "Creating Kind Cluster..."
kubectl config get-contexts kind-istio &> /dev/null || \
./kind/create &> /dev/null

# Configure Helm Repo
helm repo add istio https://istio-release.storage.googleapis.com/charts &> /dev/null
helm repo update istio &> /dev/null

# Install istio-base (CRDs)
echo "Installing istio/base..."
helm upgrade \
  --install \
  --namespace "istio-system" \
  --create-namespace \
  istio-base istio/base > /dev/null

# Install Istio Discovery
echo "Installing istio/istiod..."
helm upgrade \
  --install \
  --namespace "istio-system" \
  --create-namespace \
  istio-discovery istio/istiod \
  --values "./helm/istio-discovery/mesh-config.yaml" \
  --wait > /dev/null

# Install Istio Ingress Gateway
echo "Installing istio/gateway..."
kubectl apply \
  --filename "./helm/istio-ingress/namespace.yaml" > /dev/null

helm upgrade \
  --install \
  --namespace "istio-ingress" \
  istio-ingress istio/gateway \
  --values "./helm/istio-ingress/service.yaml" > /dev/null

# Configure Telemetry
echo "Configuring Istio Telemetry..."
kubectl apply \
  --filename "./deployments/telemetry.yaml" > /dev/null

# Configuring Add-ons
echo "Installing Prometheus..."
kubectl apply -f "${ISTIO_BASE_DIR?}/samples/addons/prometheus.yaml" > /dev/null

echo "Installing Kiali..."
kubectl apply -f "${ISTIO_BASE_DIR?}/samples/addons/kiali.yaml" > /dev/null
