#!/bin/bash
export THIS_SCRIPT_DIRECTORY=$(dirname $0)
export PATH=${PATH}:${THIS_SCRIPT_DIRECTORY}

# Directory for tests
mkdir -p ${HOME}/trash

# Create Kind Cluser
echo "Creating Kind Cluster..."
kubectl config get-contexts kind-istio &> /dev/null || \
./kind/create &> /dev/null

kubectl config get-contexts kind-istio &> /dev/null

if [ $? -ne 0 ]; then
  echo "Kind cluster not created."
  exit 1
fi

# Configure Helm Repo
helm repo add istio https://istio-release.storage.googleapis.com/charts &> /dev/null
helm repo update istio &> /dev/null

# Install istio-base (CRDs)
echo "Installing istio/base..."
helm install \
  --namespace "istio-system" \
  --create-namespace \
  istio-base istio/base > /dev/null

# Install Istio Discovery
echo "Installing istio/istiod..."
helm install \
  --namespace "istio-system" \
  --create-namespace \
  istio-discovery istio/istiod \
  --values "./helm/istio-discovery/mesh-config.yaml" \
  --values "./helm/istio-discovery/telemetry.yaml" \
  --wait > /dev/null

# Install Istio Ingress Gateway
echo "Installing istio/gateway..."
kubectl apply \
  --filename "./helm/istio-ingress/namespace.yaml" > /dev/null

helm install \
  --namespace "istio-ingress" \
  istio-ingress istio/gateway \
  --values "./helm/istio-ingress/service.yaml" > /dev/null
