#!/bin/bash
export THIS_SCRIPT_DIRECTORY=$(dirname $0)
export PATH=${PATH}:${THIS_SCRIPT_DIRECTORY}

# Install cert-manager
echo "Installing cert-manager..."
helm upgrade \
  --install \
  --namespace cert-manager \
  --create-namespace \
  cert-manager cert-manager/cert-manager \
  --set "installCRDs=true" > /dev/null

kubectl apply \
  --filename "./helm/cert-manager/cluster-issuer.yaml" > /dev/null

# httpbin Self Signed Certificate
echo "Issuing a Self Signed Certificate..."
kubectl \
  --namespace istio-ingress \
  apply \
  --filename "./helm/istio-ingress/httpbin-certificate.yaml" > /dev/null

# httpbin Deploy
echo "Deploying httpbin..."
kubectl apply \
  --filename "./deployments/httpbin/namespace.yaml" > /dev/null && \
kubectl \
  --namespace httpbin \
  apply --filename "./deployments/httpbin/" > /dev/null && \
kubectl \
  --namespace httpbin \
  wait deployment httpbin \
  --for=condition=Available \
  --timeout=360s > /dev/null

kubectl apply \
  --filename "./deployments/httpbin-istio/" > /dev/null
