#!/bin/bash
ARGOCD_INITIAL_PASSWORD=$(kubectl \
  --namespace argocd \
  get secret argocd-initial-admin-secret \
  --output jsonpath="{.data.password}" | base64 -d)

cat <<EOF

ArgoCD Initial Credentials:

  user:     admin
  password: ${ARGOCD_INITIAL_PASSWORD}
  url:      http://localhost:32080

EOF
