#!/bin/bash
POSTGRESQL_DATABASENAME="postgres"
POSTGRESQL_HOST="acid-minimal-cluster"
POSTGRESQL_PORT="5432"

POSTGRESQL_USER_NAME=$(kubectl \
  get secret postgres.acid-minimal-cluster.credentials.postgresql.acid.zalan.do \
  --output jsonpath='{.data.username}' \
| base64 -d)

POSTGRESQL_USER_PASSWORD=$(kubectl \
  get secret postgres.acid-minimal-cluster.credentials.postgresql.acid.zalan.do \
  --output jsonpath='{.data.password}' \
| base64 -d)

echo "POSTGRESQL_HOST..........: ${POSTGRESQL_HOST}"
echo "POSTGRESQL_PORT..........: ${POSTGRESQL_PORT}"
echo "POSTGRESQL_DATABASENAME..: ${POSTGRESQL_DATABASENAME}"
echo "POSTGRESQL_USER_NAME.....: ${POSTGRESQL_USER_NAME}"
echo "POSTGRESQL_USER_PASSWORD.: ${POSTGRESQL_USER_PASSWORD:0:10}"

kubectl apply -f - >/dev/null <<EOF
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
stringData:
  PGHOST:     ${POSTGRESQL_HOST}
  PGPORT:     ${POSTGRESQL_PORT}
  PGDATABASE: ${POSTGRESQL_DATABASENAME}
  PGUSER:     ${POSTGRESQL_USER_NAME}
  PGPASSWORD: ${POSTGRESQL_USER_PASSWORD}
EOF

kubectl apply -f pod.yaml > /dev/null

while ! kubectl get pods postgres-connection | grep -E "postgres-connection.*Completed" > /dev/null; do
  sleep 3
done

echo ""

kubectl logs postgres-connection -c psql

kubectl delete -f pod.yaml > /dev/null
