#!/bin/bash
POSTGRESQL_USER_NAME=$(kubectl \
  get secret postgres.acid-minimal-cluster.credentials.postgresql.acid.zalan.do \
  --output jsonpath='{.data.username}' \
| base64 -d)

POSTGRESQL_USER_PASSWORD=$(kubectl \
  get secret postgres.acid-minimal-cluster.credentials.postgresql.acid.zalan.do \
  --output jsonpath='{.data.password}' \
| base64 -d)

POSTGRESQL_DATABASENAME="postgres"
POSTGRESQL_HOST="acid-minimal-cluster"
POSTGRESQL_PORT="5432"

echo "POSTGRESQL_HOST..........: ${POSTGRESQL_HOST}"
echo "POSTGRESQL_PORT..........: ${POSTGRESQL_PORT}"
echo "POSTGRESQL_DATABASENAME..: ${POSTGRESQL_DATABASENAME}"
echo "POSTGRESQL_USER_NAME.....: ${POSTGRESQL_USER_NAME}"
echo "POSTGRESQL_USER_PASSWORD.: ${POSTGRESQL_USER_PASSWORD:0:10}"

BASE64ENCODED_POSTGRESQL_HOST=$(          echo -n "${POSTGRESQL_HOST?}"          | base64 | tr -d "\n")
BASE64ENCODED_POSTGRESQL_PORT=$(          echo -n "${POSTGRESQL_PORT?}"          | base64 | tr -d "\n")
BASE64ENCODED_POSTGRESQL_DATABASENAME=$(  echo -n "${POSTGRESQL_DATABASENAME?}"  | base64 | tr -d "\n")
BASE64ENCODED_POSTGRESQL_USER_NAME=$(     echo -n "${POSTGRESQL_USER_NAME?}"     | base64 | tr -d "\n")
BASE64ENCODED_POSTGRESQL_USER_PASSWORD=$( echo -n "${POSTGRESQL_USER_PASSWORD?}" | base64 | tr -d "\n")

kubectl apply -f - >/dev/null <<EOF
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  PGHOST:     ${BASE64ENCODED_POSTGRESQL_HOST}
  PGPORT:     ${BASE64ENCODED_POSTGRESQL_PORT}
  PGDATABASE: ${BASE64ENCODED_POSTGRESQL_DATABASENAME}
  PGUSER:     ${BASE64ENCODED_POSTGRESQL_USER_NAME}
  PGPASSWORD: ${BASE64ENCODED_POSTGRESQL_USER_PASSWORD}
EOF

kubectl apply -f pod.yaml > /dev/null

while ! kubectl get pods postgres-connection | grep -E "postgres-connection.*Completed" > /dev/null; do
  sleep 3
done

echo ""

kubectl logs postgres-connection -c psql

kubectl delete -f pod.yaml > /dev/null
