#!/bin/bash

kind create cluster \
  --image "kindest/node:v1.23.12"

helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/

helm repo update

helm search repo metrics-server/metrics-server

helm upgrade \
  --install \
  --set args={--kubelet-insecure-tls} \
  metrics-server metrics-server/metrics-server \
  --namespace kube-system \
  --wait

kubectl create namespace demo

kubectl config set-context --current --namespace demo

kubectl apply -f deploy/

kubectl wait pod \
  --for condition=Ready \
  --selector=app=hpa-example \
  --timeout 360s

kubectl run \
  -i \
  --tty load-generator \
  --rm \
  --image=busybox:1.28 \
  --restart=Never -- /bin/sh -c "while sleep 2.0; do wget -q -O- http://hpa-example-canary; done"
