---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-routes-mesh
  namespace: example
spec:
  hosts:
    - httpbin.example.svc.cluster.local

  gateways:
    - mesh

  http:
    - name: httpbin
      headers:
        request:
          add:
            X-A1-origin-1: httpbin-gateway-mesh

      route:
        - destination:
            host: httpbin.example.svc.cluster.local
            port:
              number: 8000
