server:
  config:
    resource.customizations: |
      admissionregistration.k8s.io/MutatingWebhookConfiguration:
        ignoreDifferences: |
          jsonPointers:
            - /webhooks/0/clientConfig/caBundle
            - /webhooks/0/namespaceSelector/matchExpressions
            - /webhooks/1/clientConfig/caBundle
            - /webhooks/1/namespaceSelector/matchExpressions
            - /webhooks/2/clientConfig/caBundle
            - /webhooks/2/namespaceSelector/matchExpressions
            - /webhooks/3/clientConfig/caBundle
            - /webhooks/3/namespaceSelector/matchExpressions
      admissionregistration.k8s.io/ValidatingWebhookConfiguration:
        ignoreDifferences: |
          jsonPointers:
            - /webhooks/0/clientConfig/caBundle
            - /webhooks/0/failurePolicy
