#!/bin/bash

# https://docs.crossplane.io/v2.2/get-started/install/

k3d cluster create \
  --servers 3 \
  --wait \
  --timeout 360s

for node in $(kubectl get nodes --output name); do
  kubectl wait ${node} \
    --for condition=Ready \
    --timeout=360s
done

helm repo add crossplane-stable https://charts.crossplane.io/stable

helm repo update

helm install crossplane \
  --create-namespace \
  --namespace crossplane-system \
  crossplane-stable/crossplane \
  --version 2.2.0 \
  --wait

kubectl \
  wait deployment \
    --namespace crossplane-system \
    --selector release=crossplane \
    --for condition=Available \
    --timeout=360s

kubectl get pods --namespace crossplane-system
