---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: reserved

handler: 'runc'

scheduling:
  nodeSelector:
    reserved: 'true'

  tolerations:
    - effect: NoSchedule
      key: os
      operator: Equal
      value: "linux"
