#!/bin/bash
BASE64ENCODED_RABBITMQ_HOST=$(         echo -n "${RABBITMQ_HOST?}"         | base64 | tr -d "\n") && \
BASE64ENCODED_RABBITMQ_PORT=$(         echo -n "${RABBITMQ_PORT?}"         | base64 | tr -d "\n") && \
BASE64ENCODED_RABBITMQ_VIRTUAL_HOST=$( echo -n "${RABBITMQ_VIRTUAL_HOST?}" | base64 | tr -d "\n") && \
BASE64ENCODED_RABBITMQ_USERNAME=$(     echo -n "${RABBITMQ_USERNAME?}"     | base64 | tr -d "\n") && \
BASE64ENCODED_RABBITMQ_PASSWORD=$(     echo -n "${RABBITMQ_PASSWORD?}"     | base64 | tr -d "\n") && \
kubectl apply -f - <<EOF
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
type: Opaque
data:
  RABBITMQ_HOST:         ${BASE64ENCODED_RABBITMQ_HOST}
  RABBITMQ_PORT:         ${BASE64ENCODED_RABBITMQ_PORT}
  RABBITMQ_VIRTUAL_HOST: ${BASE64ENCODED_RABBITMQ_VIRTUAL_HOST}
  RABBITMQ_USERNAME:     ${BASE64ENCODED_RABBITMQ_USERNAME}
  RABBITMQ_PASSWORD:     ${BASE64ENCODED_RABBITMQ_PASSWORD}
EOF

BASE64ENCODED_NEW_RELIC_ACCOUNT_ID=$(       echo -n "${NEW_RELIC_ACCOUNT_ID?}"       | base64 | tr -d "\n") && \
BASE64ENCODED_NEW_RELIC_LICENSE_KEY=$(      echo -n "${NEW_RELIC_LICENSE_KEY?}"      | base64 | tr -d "\n") && \
BASE64ENCODED_NEW_RELIC_API_KEY=$(          echo -n "${NEW_RELIC_API_KEY?}"          | base64 | tr -d "\n") && \
BASE64ENCODED_NEW_RELIC_LOG_LEVEL=$(        echo -n "${NEW_RELIC_LOG_LEVEL?}"        | base64 | tr -d "\n") && \
BASE64ENCODED_NEW_RELIC_APPENDER_ENABLED=$( echo -n "${NEW_RELIC_APPENDER_ENABLED?}" | base64 | tr -d "\n") && \
kubectl apply -f - <<EOF
---
apiVersion: v1
kind: Secret
metadata:
  name: newrelic
type: Opaque
data:
  NEW_RELIC_ACCOUNT_ID:       ${BASE64ENCODED_NEW_RELIC_ACCOUNT_ID}
  NEW_RELIC_LICENSE_KEY:      ${BASE64ENCODED_NEW_RELIC_LICENSE_KEY}
  NEW_RELIC_API_KEY:          ${BASE64ENCODED_NEW_RELIC_API_KEY}
  NEW_RELIC_LOG_LEVEL:        ${BASE64ENCODED_NEW_RELIC_LOG_LEVEL}
  NEW_RELIC_APPENDER_ENABLED: ${BASE64ENCODED_NEW_RELIC_APPENDER_ENABLED}
EOF
