#!/bin/bash
export THIS_SCRIPT_DIRECTORY=$(dirname $0)
export PATH=${PATH}:${THIS_SCRIPT_DIRECTORY}

echo "RABBITMQ_HOST..............: ${RABBITMQ_HOST}"
echo "RABBITMQ_PORT..............: ${RABBITMQ_PORT}"
echo "RABBITMQ_VIRTUAL_HOST......: ${RABBITMQ_VIRTUAL_HOST}"
echo "RABBITMQ_USERNAME..........: ${RABBITMQ_USERNAME}"
echo "RABBITMQ_PASSWORD..........: ${RABBITMQ_PASSWORD:0:3}"
echo "RABBITMQ_QUEUE_NAME_MAIN...: ${RABBITMQ_QUEUE_NAME_MAIN}"
echo "NEW_RELIC_ACCOUNT_ID.......: ${NEW_RELIC_ACCOUNT_ID}"
echo "NEW_RELIC_LICENSE_KEY......: ${NEW_RELIC_LICENSE_KEY:0:3}"
echo "NEW_RELIC_API_KEY..........: ${NEW_RELIC_API_KEY:0:3}"
echo "NEW_RELIC_LOG_LEVEL........: ${NEW_RELIC_LOG_LEVEL}"
echo "NEW_RELIC_APPENDER_ENABLED.: ${NEW_RELIC_APPENDER_ENABLED}"

kubectl apply \
  --namespace wasp \
  --filename "${THIS_SCRIPT_DIRECTORY}/namespace.yaml"

kubectl apply \
  --namespace wasp \
  --filename - <<EOF
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
type: Opaque
stringData:
  RABBITMQ_HOST:            "${RABBITMQ_HOST}"
  RABBITMQ_PORT:            "${RABBITMQ_PORT}"
  RABBITMQ_VIRTUAL_HOST:    "${RABBITMQ_VIRTUAL_HOST}"
  RABBITMQ_USERNAME:        "${RABBITMQ_USERNAME}"
  RABBITMQ_PASSWORD:        "${RABBITMQ_PASSWORD}"
  RABBITMQ_QUEUE_NAME_MAIN: "${RABBITMQ_QUEUE_NAME_MAIN}"
EOF

kubectl apply \
  --namespace wasp \
  --filename - <<EOF
---
apiVersion: v1
kind: Secret
metadata:
  name: newrelic
type: Opaque
stringData:
  NEW_RELIC_ACCOUNT_ID:       "${NEW_RELIC_ACCOUNT_ID}"
  NEW_RELIC_LICENSE_KEY:      "${NEW_RELIC_LICENSE_KEY}"
  NEW_RELIC_API_KEY:          "${NEW_RELIC_API_KEY}"
  NEW_RELIC_LOG_LEVEL:        "${NEW_RELIC_LOG_LEVEL}"
  NEW_RELIC_APPENDER_ENABLED: "${NEW_RELIC_APPENDER_ENABLED}"
EOF

kubectl apply \
  --namespace wasp \
  --filename "${THIS_SCRIPT_DIRECTORY}/deployment.yaml"
