# -*- mode: ruby -*-
# vi:set ft=ruby sw=2 ts=2 sts=2:

# Define the number of master and worker nodes
# If this number is changed, remember to update setup-hosts.sh script with the new hosts IP details in /etc/hosts of each VM.
MASTER_NODES_COUNT = 3
WORKER_NODES_COUNT = 2

IP_NW = "192.168.5."
MASTER_IP_START = 10
NODE_IP_START = 20

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version. Please don't change it unless you know what you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false

  # Load Balancer
  config.vm.define "loadbalancer" do |node|
    node.vm.provider "virtualbox" do |vb|
        vb.name = "kubernetes-ha-lb"
        vb.memory = 512
        vb.cpus = 1
    end
    node.vm.hostname = "loadbalancer"
    node.vm.network :private_network, ip: IP_NW + "#{MASTER_IP_START}"
	  node.vm.network "forwarded_port", guest: 22, host: 2730

    node.vm.provision "setup-hosts", :type => "shell", :path => "ubuntu/vagrant/setup-hosts.sh" do |s|
      s.args = ["enp0s8"]
    end

    #node.vm.provision "install-guest-additions", type: "shell", :path => "ubuntu/vagrant/install-guest-additions.sh"
    node.vm.provision "update-dns", type: "shell", :path => "ubuntu/update-dns.sh"
    node.vm.provision "update-system", type: "shell", :path => "ubuntu/update-system.sh"
    node.vm.provision "install-haproxy", type: "shell", :path => "ubuntu/install-haproxy.sh"

  end

  # Master Nodes - Control Plane
  (1..MASTER_NODES_COUNT).each do |i|
      config.vm.define "master-#{i}" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name = "kubernetes-ha-master-#{i}"
            vb.memory = 2048
            vb.cpus = 2
        end
        node.vm.hostname = "master-#{i}"
        node.vm.network :private_network, ip: IP_NW + "#{MASTER_IP_START + i}"
        node.vm.network "forwarded_port", guest: 22, host: "#{2730 + i}"

        node.vm.provision "setup-hosts", :type => "shell", :path => "ubuntu/vagrant/setup-hosts.sh" do |s|
          s.args = ["enp0s8"]
        end

        #node.vm.provision "install-guest-additions", type: "shell", :path => "ubuntu/vagrant/install-guest-additions.sh"
        node.vm.provision "update-dns", type: "shell", :path => "ubuntu/update-dns.sh"
        node.vm.provision "update-system", type: "shell", :path => "ubuntu/update-system.sh"
        node.vm.provision "install-docker", type: "shell", :path => "ubuntu/install-docker.sh"
      end
  
  end

  # Worker Nodes
  (1..WORKER_NODES_COUNT).each do |i|
      config.vm.define "worker-#{i}" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name = "kubernetes-ha-worker-#{i}"
            vb.memory = 2048
            vb.cpus = 2
        end
        node.vm.hostname = "worker-#{i}"
        node.vm.network :private_network, ip: IP_NW + "#{NODE_IP_START + i}"
        node.vm.network "forwarded_port", guest: 22, host: "#{2740 + i}"

        node.vm.provision "setup-hosts", :type => "shell", :path => "ubuntu/vagrant/setup-hosts.sh" do |s|
          s.args = ["enp0s8"]
        end

        #node.vm.provision "install-guest-additions", type: "shell", :path => "ubuntu/vagrant/install-guest-additions.sh"
        node.vm.provision "update-dns", type: "shell", :path => "ubuntu/update-dns.sh"
        node.vm.provision "update-system", type: "shell", :path => "ubuntu/update-system.sh"
        node.vm.provision "install-docker", type: "shell", :path => "ubuntu/install-docker.sh"        
        
        node.vm.provision "shell", run: "always",
          inline: "ip route add 10.96.0.0/16 dev enp0s8 src #{IP_NW}#{NODE_IP_START + i}"
      end
  
  end
  
end
